"use client";
import Link from "next/link";
import {FormEvent, useState} from "react";

type Result={qualified_symbol?:string;calculations?:Record<string,unknown>;ordinary_operating_company_universe_count?:number;counts_by_security_type?:Record<string,number>;mapping_readiness?:{available:number;total:number};remaining_blockers?:string[]};
export default function ModelPage(){
 const [decision,setDecision]=useState(""); const [symbol,setSymbol]=useState(""); const [report,setReport]=useState<Result|null>(null); const [factor,setFactor]=useState<Result|null>(null); const [error,setError]=useState(false);
 const timestamp=()=>new Date(decision).toISOString();
 async function readiness(e:FormEvent){e.preventDefault();setError(false);try{const r=await fetch(`/api/research/comparable-universe-readiness?decision_at=${encodeURIComponent(timestamp())}`,{cache:"no-store"});if(!r.ok)throw Error();setReport(await r.json())}catch{setError(true)}}
 async function preview(e:FormEvent){e.preventDefault();setError(false);try{const r=await fetch(`/api/research/company-factor-preview?decision_at=${encodeURIComponent(timestamp())}&qualified_symbol=${encodeURIComponent(symbol)}`,{cache:"no-store"});if(!r.ok)throw Error();setFactor(await r.json())}catch{setError(true)}}
 return <main className="research-page"><nav><span className="mark">SL</span><strong>Research foundation</strong><Link href="/">Research view</Link></nav>
 <section className="panel"><p className="eyebrow">TRACK B RESEARCH FOUNDATION — NOT A MODEL</p><h1>Comparable evidence before comparison.</h1><p><strong>NO PURCHASE RECOMMENDATION · NO CANDIDATES GENERATED · ZERO VALIDATION CREDIT</strong></p><p>The active catalogue is not automatically a fair comparison group. Banks, insurers, property trusts, BDCs, funds, SPACs, bundled units, foreign issuers, development-stage businesses, and special structures need separately registered methods and are disclosed rather than silently discarded.</p><div className="score-grid"><div><span>Track A</span><b>Frozen unchanged</b></div><div><span>Track B</span><b>Not a model</b></div><div><span>Rankings / Top 3</span><b>None</b></div></div></section>
 <section className="panel"><h2>Materialized evidence progress</h2><p>Classification coverage, comparable-universe exclusions, factor evidence, mapping review, enrichment readiness, and corporate-action coverage are point-in-time research evidence. Only ordinary US operating companies enter this initial research universe. Missing debt is unknown—not zero. Verified no-action coverage differs from a missing event row. Value and financial-strength calculations are independent, so unavailable enterprise value does not erase valid market-cap factors.</p><form className="research-form" onSubmit={readiness}><label>Point-in-time decision (UTC)<input required type="datetime-local" value={decision} onChange={e=>setDecision(e.target.value)}/></label><button>Inspect readiness</button></form>{report&&<><p>Ordinary-company universe: <b>{report.ordinary_operating_company_universe_count}</b> · Mapping ready: <b>{report.mapping_readiness?.available}/{report.mapping_readiness?.total}</b></p><pre>{JSON.stringify(report.counts_by_security_type,null,2)}</pre><p>Remaining blockers: {report.remaining_blockers?.join(", ")||"none reported"}</p></>}</section>
 <section className="panel"><h2>Raw company mathematics</h2><p>This lookup returns inputs, provenance, raw calculations, and withholding reasons only—never a percentile, score, rank, candidate, fair value, or recommendation.</p><form className="research-form" onSubmit={preview}><label>Exchange-qualified symbol<input required placeholder="AAPL.US" value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())}/></label><button>Inspect raw factors</button></form>{factor&&<pre>{JSON.stringify(factor.calculations,null,2)}</pre>}{error&&<p className="notice warning">Evidence is unavailable or the request was safely withheld.</p>}</section>
 </main>}
