"use client";
import Link from "next/link";
import {FormEvent, useState} from "react";

type Row={preview_rank:number;qualified_symbol:string;company_name:string;price_percentile:number;price_contribution:number;dilution_percentile:number;dilution_contribution:number;combined_score:number;price_date:string;diluted_share_growth:number;context_score_effect:string};
type Report={labels:string[];decision_at:string;model_version:string;configuration_hash:string;registration_timestamp:string;eligible_universe_count:number;scored_count:number;withheld_count:number;preview_entries:Row[];prospective_vintages_created:number;validation_observations_added:number;recommendations_generated:number};
const pct=(n:number)=>`${(n*100).toFixed(2)}%`;
export default function ModelPage(){
 const [decision,setDecision]=useState(""); const [report,setReport]=useState<Report|null>(null); const [reconstruction,setReconstruction]=useState<Record<string,unknown>|null>(null); const [error,setError]=useState("");
 async function load(e:FormEvent){e.preventDefault();setError("");const at=new Date(decision).toISOString();
  const [p,r]=await Promise.all([fetch(`/api/research/model-laboratory/preview?decision_at=${encodeURIComponent(at)}`,{cache:"no-store"}),fetch(`/api/research/model-laboratory/september-reconstruction?decision_at=${encodeURIComponent("2026-09-30T23:59:59Z")}`,{cache:"no-store"})]);
  if(!p.ok||!r.ok){setError("The model laboratory safely withheld unavailable evidence.");return} setReport(await p.json());setReconstruction(await r.json());}
 return <main className="research-page"><nav><span className="mark">SL</span><strong>Model Laboratory</strong><Link href="/">Research view</Link></nav>
  <section className="hero compact"><p className="eyebrow">INDICATIVE PRE-VINTAGE PREVIEW · NOT VALIDATION</p><h1>Frozen mathematics,<br/><span>visible and read only.</span></h1><p className="lede">NO INVESTMENT RECOMMENDATION. 0.90 × price percentile + 0.10 × dilution percentile.</p></section>
  <form className="panel research-form" onSubmit={load}><label>Decision timestamp (UTC)<input required type="datetime-local" value={decision} onChange={e=>setDecision(e.target.value)}/></label><button>Build indicative preview</button></form>{error&&<p className="notice warning">{error}</p>}
  {report&&<div className="brief-stack"><section className="panel"><p className="eyebrow">{report.labels.join(" · ")}</p><h2>{report.model_version}</h2><p><code>{report.configuration_hash}</code></p><p>Registered {report.registration_timestamp} · Known at {report.decision_at}</p><div className="score-grid"><div><span>Eligible universe</span><b>{report.eligible_universe_count}</b></div><div><span>Scored</span><b>{report.scored_count}</b></div><div><span>Withheld</span><b>{report.withheld_count}</b></div></div></section>
  <section className="panel"><p className="eyebrow">INDICATIVE TOP-3 · NOT A PAPER SELECTION</p><div className="model-table"><table><thead><tr><th>Rank / company</th><th>Price × 90%</th><th>Dilution × 10%</th><th>Combined</th></tr></thead><tbody>{report.preview_entries.map(x=><tr key={x.qualified_symbol}><td><b>#{x.preview_rank} {x.qualified_symbol}</b><small>{x.company_name}<br/>Price {x.price_date}</small></td><td>{pct(x.price_percentile)} → {pct(x.price_contribution)}</td><td>{pct(x.dilution_percentile)} → {pct(x.dilution_contribution)}<small>Growth {pct(x.diluted_share_growth)}</small></td><td><b>{x.combined_score.toFixed(6)}</b><small>{x.context_score_effect}</small></td></tr>)}</tbody></table></div></section>
  <section className="panel"><p className="eyebrow">CONTEXT VERSUS SCORE</p><h2>Context never changes the frozen equation</h2><p>SEC citations, risks, and missing contextual information explain evidence only. Price-only compares the same eligible cohort by price percentile. Equal-weight compares the same eligible US universe with identical decision timing.</p></section>
  <section className="panel"><p className="eyebrow">SEPTEMBER RECONSTRUCTION</p><h2>{String(reconstruction?.reconstruction_status??"unavailable")}</h2><p>Zero validation credit. Later-retrieved evidence cannot repair the boundary.</p></section>
  <section className="panel"><p className="eyebrow">VALIDATION LEDGER</p><h2>Evidence remains separated</h2><ul><li>Failed retrospective 40% fundamentals experiment: frozen failure.</li><li>Exploratory diagnostics: not model selection.</li><li>Current 90/10 prospective hypothesis: unvalidated.</li><li>Official prospective vintages: {report.prospective_vintages_created}.</li><li>Matured 126-session outcomes: 0.</li><li>Matured 252-session outcomes: 0.</li></ul><p>126 sessions ≈ six trading months · 252 sessions ≈ twelve trading months. Outcomes mature only at exact sessions.</p><p>Validation observations: {report.validation_observations_added} · Recommendations: {report.recommendations_generated}</p></section></div>}
 </main>}
